#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Path
export PATH=/usr/local/bin:$PATH:$HOME/Library/Python/3.4/bin

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
. /Users/brouchouse/Library/Python/3.4/lib/python/site-packages/powerline/bindings/zsh/powerline.zsh

